on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy to HubSpot
        run: npx --yes --package=@hubspot/cli@latest hs upload src cms-theme-boilerplate --use-env
        env:
          HUBSPOT_PORTAL_ID: ${{ secrets.hubspot_portal_id }}
          HUBSPOT_PERSONAL_ACCESS_KEY: ${{ secrets.hubspot_personal_access_key }}