on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create HubSpot Config File
        run: |
          printf 'defaultPortal: %s\nportals:\n  - portalId: %s\n    authType: personalaccesskey\n    personalAccessKey: %s\n' \
            '${{ secrets.hubspot_portal_id }}' \
            '${{ secrets.hubspot_portal_id }}' \
            '${{ secrets.hubspot_personal_access_key }}' > hubspot.config.yml

      - name: Deploy to HubSpot
        run: npx --yes --package=@hubspot/cli@latest hs upload src cms-theme-boilerplate --account ${{ secrets.hubspot_portal_id }}